// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "adder": Application Contexts
//
// Command:
// $ goagen
// --design=github.com/yu-ichiko/goa-security-example/design
// --out=$(GOPATH)/src/github.com/yu-ichiko/goa-security-example
// --version=v1.3.1

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

// GetOperandsContext provides the operands get action context.
type GetOperandsContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
}

// NewGetOperandsContext parses the incoming request URL and body, performs validations and creates the
// context used by the operands controller get action.
func NewGetOperandsContext(ctx context.Context, r *http.Request, service *goa.Service) (*GetOperandsContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := GetOperandsContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *GetOperandsContext) OK(resp []byte) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "text/plain")
	}
	ctx.ResponseData.WriteHeader(200)
	_, err := ctx.ResponseData.Write(resp)
	return err
}
