// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "adder": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/yu-ichiko/goa-security-example/design
// --out=$(GOPATH)/src/github.com/yu-ichiko/goa-security-example
// --version=v1.3.1

package app
